language: python

python:
  - "3.8"
  - "3.9"

# command to install dependencies
install:

  # Install MDF
  - git clone https://github.com/ModECI/MDF.git
  - cd MDF
  - python setup.py install
  - cd -

  # Check pyNeuroML installed
  - pynml -h



script:
  ###       Run main tests

  #- ./test_all.sh
  - pip freeze  # List currently installed Python packages
