language: python

python:
  - "3.8"
  - "3.9"

# command to install dependencies
install:

  # Install MDF
  - git clone https://github.com/ModECI/MDF.git
  - cd MDF
  - python setup.py install
  - cd -

  # Install pyNeuroML
  - pip install pyneuroml
  - pynml -h



script:
  #  Run NeuroML tests

  - cd NeuroML
  - ./regenerateAndTest.sh

  # List currently installed Python packages
  - pip freeze
